source 'https://github.com/CocoaPods/Specs.git'

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do

pod 'SDWebImage'
pod 'DFImageManager', :git => 'https://github.com/dapulse/DFImageManager'
pod 'DFImageManager/GIF'
pod 'DACircularProgress'
pod 'pop'

end
